<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
		<TargetFrameworks>net7.0-android;net6.0-android;</TargetFrameworks>
		<SupportedOSPlatformVersion>21</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<PropertyGroup>
		<PackageId>Anjo.Android.Facebook.Applinks</PackageId>
		<PackageVersion>16.1.3</PackageVersion>
		<AssemblyVersion>16.1.3</AssemblyVersion>
		<FileVersion>16.1.3</FileVersion>
		<Version>16.1.3</Version>
		<Title>Anjo Android Facebook.Applinks SDK</Title>
		<Authors>Wael Anjo</Authors>
		<Owners>Wael Anjo</Owners>
		<PackageProjectUrl>https://github.com/mhdwaelanjo/Anjo.Android.Facebook</PackageProjectUrl>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<Description>.NET for Android (formerly Xamarin.Android) Binding Library - Facebook.Applinks SDK</Description>
		<PackageReleaseNotes>Facebook.Applinks SDK v16.1.3</PackageReleaseNotes>
		<Copyright>Copyright (c) 2023 Wael Anjo</Copyright>
		<PackageTags>Xamarin.Android, Facebook, Android, social login, Advertising</PackageTags>
		<Summary>.NET for Android (formerly Xamarin.Android) Binding Library - Facebook.Applinks SDK</Summary>
		<!-- Include symbol files (*.pdb) in the built .nupkg -->
		<AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
	</PropertyGroup>
	<ItemGroup>
	  <None Remove="Jars\facebook-applinks-16.1.3.aar" />
	</ItemGroup>
	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.5.0.2" />
    <PackageReference Include="Xamarin.AndroidX.Legacy.Support.Core.Utils" Version="1.0.0.16" />
    <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk7" Version="1.8.10" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FacebookCore\FacebookCore.csproj" />
  </ItemGroup>
</Project>